spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  application:
    name: dev
  datasource:
    url: 
    username: 
    password: 
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#security
security:
  jwt:
    expiration-minutes: 30
    secret-key: 

#general config
logging:
  level:
    org:
      hibernate:
        type: trace
