spring:
  application:
    name: dev
  datasource:
    url: jdbc:mysql://localhost:3306/municipios?user=root
    username: root
    password: Juanceto01

#security
security:
  jwt:
    expiration-minutes: 30
    secret-key: bXktU2VjcmV0LUtleS0xMjM0NTIzMTItMzIxMjM9MTIzNDUxMg==
#general config

