spring:
  application:
    name: dev
  datasource:
    url: 
    username: 
    password: 

#security
security:
  jwt:
    expiration-minutes: 30
    secret-key: bXktU2VjcmV0LUtleS0xMjM0NTIzMTItMzIxMjM9MTIzNDUxMg==
#general config

